export const GET_CAROUSEL = 'GET_CAROUSEL';
export const UPDATE_CAROUSEL = 'UPDATE_CAROUSEL';
export const SET_THONG_TIN_CAROUSEL = 'SET_THONG_TIN_CAROUSEL';


export const SET_DANH_SACH_PHIM = 'SET_DANH_SACH_PHIM';
export const SET_PHIM_DANG_CHIEU = 'SET_PHIM_DANG_CHIEU';
export const SET_PHIM_SAP_CHIEU = 'SET_PHIM_SAP_CHIEU';
export const SET_CHI_TIET_PHIM = 'SET_CHI_TIET_PHIM';
export const SET_THONG_TIN_PHIM = 'SET_THONG_TIN_PHIM';


export const GET_HE_THONG_RAP_CHIEU = 'GET_HE_THONG_RAP_CHIEU';
export const GET_CUM_RAP_CHIEU = 'GET_CUM_RAP_CHIEU';
export const GET_DANH_SACH_TINH_THANH = 'GET_DANH_SACH_TINH_THANH';


export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION'
export const DANG_KY_ACTION = 'DANG_KY_ACTION'
export const LAY_LAI_MAT_KHAU_ACTION = "LAY_LAI_MAT_KHAU_ACTION";

export const LAY_DANH_SACH_NGUOI_DUNG = 'LAY_DANH_SACH_NGUOI_DUNG'
export const LAY_CHI_TIET_NGUOI_DUNG = 'LAY_CHI_TIET_NGUOI_DUNG'
export const TIM_KIEM_NGUOI_DUNG = 'TIM_KIEM_NGUOI_DUNG'


export const LAY_DANH_SACH_LICH_CHIEU = 'LAY_DANH_SACH_LICH_CHIEU'
export const LAY_LICH_CHIEU_THEO_PHIM = 'LAY_LICH_CHIEU_THEO_PHIM'
export const LAY_CHI_TIET_LICH_CHIEU = 'LAY_CHI_TIET_LICH_CHIEU'
export const LAY_DANH_SACH_GHE = 'LAY_DANH_SACH_GHE'
export const CHON_GHE = 'CHON_GHE'
export const XAC_NHAN_DON_HANG = 'XAC_NHAN_DON_HANG'
export const DAT_VE = 'DAT_VE'
export const LAY_DANH_SACH_DON_HANG_THEO_USER = 'LAY_DANH_SACH_DON_HANG_THEO_USER'
export const SET_THONG_TIN_DAT_VE = 'SET_THONG_TIN_DAT_VE'
export const DAT_VE_HOAN_TAT = 'DAT_VE_HOAN_TAT'
export const LAY_DOANH_THU = 'LAY_DOANH_THU'


export const GET_TIN_TUC = 'GET_TIN_TUC';
export const GET_CHI_TIET_TIN_TUC = 'GET_CHI_TIET_TIN_TUC';
export const GET_BINH_LUAN = 'GET_BINH_LUAN';
export const GET_BINH_LUAN_DETAIL = 'GET_BINH_LUAN_DETAIL';
export const GET_BINH_LUAN_PHIM = 'GET_BINH_LUAN_PHIM';
export const GET_BINH_LUAN_DETAIL_PHIM = 'GET_BINH_LUAN_DETAIL_PHIM';

export const DISPLAY_LOADING = 'DISPLAY_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'



export const CHUYEN_TAB = 'CHUYEN_TAB'
export const CHUYEN_TAB_ACTIVE = 'CHUYEN_TAB_ACTIVE'

export const LAY_KET_QUA_TIM_KIEM = 'LAY_KET_QUA_TIM_KIEM'

//Feedback
export const LAY_FEEDBACK = 'LAY_FEEDBACK'
export const LAY_CHITIET_FEEDBACK = 'LAY_CHITIET_FEEDBACK'







